### ISSUE TITLE
Online version not working

### ISSUE THREAD

**Issue by kosli** [kirillgroshkov/kg-releases#1]
I just found your post on reddit and wanted to try it out. Unfortunately currently I get only a pop-up window which shortly shows a github page and the it closes automatically without any interaction... and the homepage is aftewards still the same, even after reloading the page.

**Comment by kirillgroshkov** [comment]
@kosli Which browser are you using? Which OS? Is it mobile or desktop?

I suggest to try to clear localStorage and try again.

Or it would help if you could look into browser console and post here what's there, especially if there are any errors.

I will gladly help if I know more info!

I plan to install Sentry automatic js error monitoring later to catch such cases automatically.
