### ISSUE TITLE
Feature request. Webhook

### ISSUE THREAD

**Issue by antonmarin** [kirillgroshkov/kg-releases#10]
My scenario: i've got several docker images for tools, which don't have own. It would be great if i was able to setup smth to trigger building images. So scenario should be:
1. I have smth dependent on github release
2. I setup Releases app
3. When github release happens smth receives webhook

**Comment by kirillgroshkov** [comment]
Hello @antonmarin,
Thanks for the interest in my project!

I'll consider this feature request, but no immediate plans or promises to implement it.

**Comment by AGSPhoenix** [comment]
Seconding this. I have automatic updates for a Chocolatey package I maintain 90% cobbled together, now I just need some service that will trigger the webhook when a new build comes out.
