### ISSUE TITLE
New starred repositories

### ISSUE THREAD

**Issue by pinpins** [kirillgroshkov/kg-releases#8]
Hello,

After starring some more repos on git, those are not fetched in a tool. not incorporated in release history

**Comment by kirillgroshkov** [comment]
Strange, they should. In every internal cron invocation it goes through all users one by one, fetches the list of stars (if it's changed since last time) and goes through all repos.

What it doesn't do - it doesn't fetch past releases for such new repos, only new ones. Maybe that's what you meant?

**Comment by kirillgroshkov** [comment]
If you think you're missing some repos in history AFTER you starred them (in the future) - please provide couple of examples and I can try to debug it
